# Generated by Django 2.0 on 2020-04-21 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmatSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='gmatmodel',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gmatmodel',
            name='file',
            field=models.FileField(null=True, upload_to='gmat/%Y/%m%d/'),
        ),
        migrations.AlterField(
            model_name='gmatmodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmat.GmatSubject'),
        ),
    ]
