# Generated by Django 2.0 on 2020-04-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmat', '0002_auto_20200422_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmatsubject',
            name='name',
            field=models.CharField(choices=[('1', 'Quant'), ('2', 'Verbal'), ('3', 'IR'), ('4', 'AWA')], max_length=30),
        ),
    ]
