# Generated by Django 2.0 on 2020-04-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmat', '0003_auto_20200422_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmatmodel',
            name='subject',
            field=models.CharField(choices=[('1', 'Quant'), ('2', 'Verbal'), ('3', 'IR'), ('4', 'AWA')], max_length=30),
        ),
        migrations.DeleteModel(
            name='GmatSubject',
        ),
    ]
